### ISSUE TITLE
Fails to run on internal server

### ISSUE THREAD

**Issue by martmists-gh** [Gunpowder-MC/Gunpowder#116]
Log: https://justpaste.it/68a32
Error: 
```
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: org.apache.logging.slf4j.SLF4JServiceProvider not a subtype
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1236)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1383)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:104)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.slf4j.LoggerFactory.bind(LoggerFactory.java:147)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:418)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:404)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:353)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.SQLLogKt.<clinit>(SQLLog.kt:14)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.Transaction.<init>(Transaction.kt:59)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager.newTransaction(ThreadLocalTransactionManager.kt:29)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:170)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:194)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:193)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:151)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:123)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:121)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at io.github.gunpowder.entities.database.AbstractDatabase$createThread$1.invoke(AbstractDatabase.java:66)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at io.github.gunpowder.entities.database.AbstractDatabase$createThread$1.invoke(AbstractDatabase.java:61)
[19:46:08] [Gunpowder Database Thread/INFO]: [STDERR]: at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by Miss-Naru** [comment]
I have the exact same error
