### ISSUE TITLE
modpack crashes when i add gunpowder api to my modpack

### ISSUE THREAD

**Issue by TheRanker** [Gunpowder-MC/Gunpowder#129]
**Information**
- Minecraft Version: 1.18.1
- Fabric API Version: fabric-api-0.46.4+1.18.jar
- OS: Windows
- over 300+

**Describe the issue**
game crashes when i add gunpowder api with a patchouli error.

**Crash/Error logs**
[19:14:38] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: org.apache.logging.slf4j.SLF4JServiceProvider not a subtype
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: org.apache.logging.slf4j.SLF4JServiceProvider not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:593) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[?:?]
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[?:?]
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[?:?]
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:104) ~[org_slf4j_slf4j-api-2.0.0-alpha5-dabdb799dd555bb7.jar:?]
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:147) ~[org_slf4j_slf4j-api-2.0.0-alpha5-dabdb799dd555bb7.jar:?]
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139) ~[org_slf4j_slf4j-api-2.0.0-alpha5-dabdb799dd555bb7.jar:?]
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421) ~[org_slf4j_slf4j-api-2.0.0-alpha5-dabdb799dd555bb7.jar:?]
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407) ~[org_slf4j_slf4j-api-2.0.0-alpha5-dabdb799dd555bb7.jar:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356) ~[org_slf4j_slf4j-api-2.0.0-alpha5-dabdb799dd555bb7.jar:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382) ~[org_slf4j_slf4j-api-2.0.0-alpha5-dabdb799dd555bb7.jar:?]
	at net.minecraft.class_310.<clinit>(class_310.java:268) ~[client-intermediary.jar:?]
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.18.1-65-FABRIC.jar:?]
	at net.minecraft.class_6396.handler$gkl000$patchouli_addContext(class_6396.java:1016) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more

**To Reproduce**
1. Go to '...'https://www.curseforge.com/minecraft/modpacks/rankersmp-exploratory-revelations
2. add gunpowder api mod
3. load game

**Expected behavior**
game loads correctly

**Additional context**
https://pastebin.ubuntu.com/p/mJKPKXfQft/

**Comment by rpmm24** [comment]
Are you asking why a serverside mod is crashing a clientside modpack?

**Comment by Martmists-GH** [comment]
I don't know quite what causes this behavior but it seems to only occur on the client. On servers it should run just fine.

**Comment by rpmm24** [comment]
id argue this mod isnt meant to be used client side anyway? it seems like on your mod pack download you have a server and client versions  why not just not have it in the client version? not trying to be dismissive just wondering.

**Comment by Martmists-GH** [comment]
It's designed to (naively) support client-side use too for use in opening to LAN for setups like Hamachi for those who are limited to that solution. This service bug has been a reported issue for months but nobody seems to know what causes it.

**Comment by Martmists-GH** [comment]
Closing as duplicate of #116
