### ISSUE TITLE
gunpowder prelunch error

### ISSUE THREAD

**Issue by Venserus** [Gunpowder-MC/Gunpowder#131]
**Information**
1.18
- Fabric API Version: fabric-api-0.43.1

**Describe the issue**
one day it just stoped working and i dont know why

**Crash/Error logs**

[main/ERROR]: A mod crashed on startup!
135 | net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'gunpowder-base'!
136 | at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.4.jar:?]
137 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.4.jar:?]
138 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.4.jar:?]
139 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
140 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
141 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
142 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
143 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:67) [fabric-loader-0.14.4.jar:?]
144 | Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'gunpowder-base'!
145 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.4.jar:?]
146 | at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.4.jar:?]
147 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.4.jar:?]
148 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.4.jar:?]
149 | at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.4.jar:?]
150 | ... 7 more
151 | Caused by: java.lang.ExceptionInInitializerError
152 | at io.github.gunpowder.mod.GunpowderPrelaunchHook.onPreLaunch(GunpowderPrelaunchHook.kt:32) ~[gunpowder-base-1.1.1.1+1.18.1.jar:?]
153 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.4.jar:?]
154 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.4.jar:?]
155 | at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.4.jar:?]
156 | ... 7 more
157 | Caused by: java.lang.RuntimeException: Failed to load Classloader fields
158 | at io.github.gunpowder.mod.PrelaunchHook.<clinit>(PrelaunchHook.kt:50) ~[gunpowder-base-1.1.1.1+1.18.1.jar:?]
159 | at io.github.gunpowder.mod.GunpowderPrelaunchHook.onPreLaunch(GunpowderPrelaunchHook.kt:32) ~[gunpowder-base-1.1.1.1+1.18.1.jar:?]
160 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.4.jar:?]
161 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.4.jar:?]
162 | at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.4.jar:?]
163 | ... 7 more
164 | Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
165 | at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
166 | at io.github.gunpowder.mod.PrelaunchHook.<clinit>(PrelaunchHook.kt:47) ~[gunpowder-base-1.1.1.1+1.18.1.jar:?]
167 | at io.github.gunpowder.mod.GunpowderPrelaunchHook.onPreLaunch(GunpowderPrelaunchHook.kt:32) ~[gunpowder-base-1.1.1.1+1.18.1.jar:?]
168 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.4.jar:?]
169 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.4.jar:?]
170 | at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.4.jar:?]
171 | ... 7 more
172
[main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'gunpowder-base'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:67) [fabric-loader-0.14.4.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'gunpowder-base'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:[162](https://aternos.org/log/#L162)) ~[fabric-loader-0.14.4.jar:?]
	... 7 more
Caused by: java.lang.ExceptionInInitializerError
	at io.github.gunpowder.mod.GunpowderPrelaunchHook.onPreLaunch(GunpowderPrelaunchHook.kt:32) ~[gunpowder-base-1.1.1.1+1.18.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.4.jar:?]
	... 7 more
Caused by: java.lang.RuntimeException: Failed to load Classloader fields
	at io.github.gunpowder.mod.PrelaunchHook.<clinit>(PrelaunchHook.kt:50) ~[gunpowder-base-1.1.1.1+1.18.1.jar:?]
	at io.github.gunpowder.mod.GunpowderPrelaunchHook.onPreLaunch(GunpowderPrelaunchHook.kt:32) ~[gunpowder-base-1.1.1.1+1.18.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.4.jar:?]
	... 7 more
Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
	at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
	at io.github.gunpowder.mod.PrelaunchHook.<clinit>(PrelaunchHook.kt:47) ~[gunpowder-base-1.1.1.1+1.18.1.jar:?]
	at io.github.gunpowder.mod.GunpowderPrelaunchHook.onPreLaunch(GunpowderPrelaunchHook.kt:32) ~[gunpowder-base-1.1.1.1+1.18.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.4.jar:?]
	... 7 more

**Comment by Martmists-GH** [comment]
This is an issue with newer versions of fabric launcher. This is fixed in the 1.18.2 version, and I'll be trying to update and release all modules this weekend.

**Comment by WaddleWaddle-sakura** [comment]
Sorry if what you said was a simple answer and i'm just slow. But do you plan on fixing it so 1.18.1 can run it? We tried using FLAN until realizing it needs the gunpowder for people to buy claimblocks, sadly getting the same error cannot be used.

**Comment by Martmists-GH** [comment]
For 1.18.1, downgrade the version of Fabric Launcher you're using. I can't say what version will or won't work.
