### ISSUE TITLE
Server unable to start due to gunpower utilities .

### ISSUE THREAD

**Issue by wabotak** [Gunpowder-MC/Gunpowder#88]
**Information**
- Minecraft Version: [1.16.2]
- Fabric API Version: [fabric-api-0.20.1+build.401-1.16]
- OS: [CENTOS 7]
- Other installed mods: [Craft to Exile : Harmony]

Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'gunpowder-base'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:93) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: io/github/ladysnake/pal/Pal
	at io.github.gunpowder.commands.FlightCommand.<clinit>(FlightCommand.java:38) ~[gunpowder-utilities-1.0.1+gunpowder.0.2.9.mc.1.16.2.jar:?]
	at io.github.gunpowder.GunpowderUtilitiesModule.registerCommands(GunpowderUtilitiesModule.java:40) ~[gunpowder-utilities-1.0.1+gunpowder.0.2.9.mc.1.16.2.jar:?]
	at io.github.gunpowder.mod.AbstractGunpowderMod.initialize(AbstractGunpowderMod.java:76) ~[gunpowder-base-0.2.10+1.16.2.jar:?]
	at io.github.gunpowder.mod.server.GunpowderServerMod.onInitializeServer(GunpowderServerMod.java:43) ~[gunpowder-base-0.2.10+1.16.2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: io.github.ladysnake.pal.Pal
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_272]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_272]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_272]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_272]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_272]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_272]
	at io.github.gunpowder.commands.FlightCommand.<clinit>(FlightCommand.java:38) ~[gunpowder-utilities-1.0.1+gunpowder.0.2.9.mc.1.16.2.jar:?]
	at io.github.gunpowder.GunpowderUtilitiesModule.registerCommands(GunpowderUtilitiesModule.java:40) ~[gunpowder-utilities-1.0.1+gunpowder.0.2.9.mc.1.16.2.jar:?]
	at io.github.gunpowder.mod.AbstractGunpowderMod.initialize(AbstractGunpowderMod.java:76) ~[gunpowder-base-0.2.10+1.16.2.jar:?]
	at io.github.gunpowder.mod.server.GunpowderServerMod.onInitializeServer(GunpowderServerMod.java:43) ~[gunpowder-base-0.2.10+1.16.2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more

**Comment by MaryWeeb** [comment]
Install PlayerAbilityLib.

**Comment by wabotak** [comment]
thanks you sir for helping ! now i make all those player can fly2 around
